package ejercicios12;/*
package ejercicios12;


public class Ejercicio3 {
  /*Producir치 si o si el print del finally.
  Adem치s, como hereda de la clase exception imprimir치 el print
  del catch


    public static void main(String[] args) {

        class Prueba extends Exception { }
        class Main {
            public static void main(String args[]) {
                try {
                    throw new Prueba();
                }
                catch(Prueba ex) {
                    System.out.println("Se produjo una excepci칩n Prueba.");
                }
                finally {
                    System.out.println("Estoy dentro del bloque finally.");
                }
            }
        }
    }
}*/
